name: fruit_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  firebase_auth: ^6.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^7.2.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Regular.ttf

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
