// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1lH03dfT_Inyk0jOAxaeqauJ-_Rv75Cs',
    appId: '1:861567142322:web:42210e73678ee392933cab',
    messagingSenderId: '861567142322',
    projectId: 'fruit-hub-app-2025',
    authDomain: 'fruit-hub-app-2025.firebaseapp.com',
    storageBucket: 'fruit-hub-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoVxVrYIVrPbEO1OO-aVxw1MmgKj9wS9k',
    appId: '1:861567142322:android:e46bd080a219433d933cab',
    messagingSenderId: '861567142322',
    projectId: 'fruit-hub-app-2025',
    storageBucket: 'fruit-hub-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcb4OStS9O3g9iNyVhxcVJ6FCeN8cn-u0',
    appId: '1:861567142322:ios:2225a6ad31cbfc05933cab',
    messagingSenderId: '861567142322',
    projectId: 'fruit-hub-app-2025',
    storageBucket: 'fruit-hub-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );
}
